### PR TITLE
feat: sm-75 create divider component

### PR DESCRIPTION
**Pull request by Suryansh-Simform**
## Description

This pull request introduces a flexible and customizable `Divider` component. The `Divider` enhances content separation and visual organization across the application, supporting multiple variants for styling, alignment, and orientation.

## Features

- **Variant Control**: 
  - Options: `fullWidth`, `inset`, `middle`
  - Controls the width and positioning of the divider.
  
- **Alignment Control**: 
  - Options: `horizontal`, `vertical`
  - Sets the orientation of the divider.
  
- **Type Control**: 
  - Options: `solid`, `dashed`, `dotted`
  - Specifies the style of the divider.

- **Text Alignment Control**: 
  - Options: `left`, `right`, `center`
  - Aligns text inside the divider for better UI flexibility.

Divider_example_1
Divider_example_4
Divider_Example_2
Divider_Example_3

### CODE REVIEW

**Comment by VatsalDave2102** [comment]
Could we go for a better naming convention for `textAlign` options that are `left`, `right` and `center`. For `horizontal` variant they seem perfect but for `vertical`, they create confusion. We can have `top`, `bottom` and `center` for that. This is achievable using discriminated unions in typescript.

**Comment by Suryansh-Simform** [comment]
> Could we go for a better naming convention for `textAlign` options that are `left`, `right` and `center`. For `horizontal` variant they seem perfect but for `vertical`, they create confusion. We can have `top`, `bottom` and `center` for that. This is achievable using discriminated unions in typescript.


@VatsalDave2102  You're right, we could use options like top, right, and left—I considered this as well. However, if you look at examples like Material UI and Ant Design etc, they don’t offer `text-align` options like top, bottom, or center for vertical alignment.
Screenshot from 2024-09-30 10-17-29
Screenshot from 2024-09-30 10-30-48

but if you want I can take a look and try to implement as you mentioned

**Comment by VatsalDave2102** [comment]
> @VatsalDave2102 You're right, we could use options like top, right, and left—I considered this as well. However, if you look at examples like Material UI and Ant Design etc, they don’t offer `text-align` options like top, bottom, or center for vertical alignment. 

You're correct, they have not provided options for `top` and `bottom`. But they also have not implemented the styles for that in `vertical` orientation. i.e.
```
<Divider textAlign="left" orientation="vertical">Content</Divider>
```
The `Content` would stay in center even though we have given text align `left`. On the other hand, we have implemented styles for `vertical` orientation. Hence I suggested to have a better naming convention. Or else we could also follow a similar pattern like MUI, to not provide styles for `vertical` orientation.

**Comment by Suryansh-Simform** [comment]
> > @VatsalDave2102 You're right, we could use options like top, right, and left—I considered this as well. However, if you look at examples like Material UI and Ant Design etc, they don’t offer `text-align` options like top, bottom, or center for vertical alignment.
> 
> You're correct, they have not provided options for `top` and `bottom`. But they also have not implemented the styles for that in `vertical` orientation. i.e.
> 
> ```
> <Divider textAlign="left" orientation="vertical">Content</Divider>
> ```
> 
> The `Content` would stay in center even though we have given text align `left`. On the other hand, we have implemented styles for `vertical` orientation. Hence I suggested to have a better naming convention. Or else we could also follow a similar pattern like MUI, to not provide styles for `vertical` orientation.

@VatsalDave2102  Agreed will implement the changes

**Review by kashyap27102 — CHANGES_REQUESTED** [review]

**Pull request merged**
